const path = {
    HOME: "/",
    LOGIN: '/login',
    MY_MUSIC: '/mymusic',
    ALBUM__TITLE__PID: '/album/:title/:pid',
    PLAYLIST__TITLE__PID: '/playlist/:title/:pid',
    TOP100 : "/top100",
    FOLLOW: "/follow",
    NEWRELEASE: "/moi-phat-hanh",
    MV: "/mv",
    ZINGCHART: "/zing-chart",
    PERSONAL: "/personal",
    Search: "/search",
    MVideo: "/video-clip/:alias/:id",
    ARTIST: "/:alias",
    ARTIST_2 : "/nghe-si/:alias",
    ARTISTSONG: "/:alias/bai-hat",
    ARTISTSONG_2: "/nghe-si/:alias/bai-hat",
    SINGLE_EP : "/:alias/single",
    SINGLE_EP_2: "/nghe-si/:alias/single",
    ARTIST_ALBUM: "/:alias/album",
    ARTIST_ALBUM_2: "/nghe-si/:alias/album",
    ARTIST_VIDEO : "/:alias/video",
    ARTIST_VIDEO_2 : "/nghe-si/:alias/video",
}

export default path